### ISSUE TITLE
The download link of pre-trained model  return a 404 error

### ISSUE THREAD

**Issue by ynanwu** [Yushu-Li/OWTTT#3]
Could you please provide the download link for the pre-trained ResNet50 again? The following two download links return a 404 error. Thanks.
“mkdir -p results/cifar10_joint_resnet50 && cd results/cifar10_joint_resnet50
gdown https://drive.google.com/uc?id=1TWiFJY_q5uKvNr9x3Z4CiK2w9Giqk9Dx && cd ../..
mkdir -p results/cifar100_joint_resnet50 && cd results/cifar100_joint_resnet50
gdown https://drive.google.com/uc?id=1-8KNUXXVzJIPvao-GxMp2DiArYU9NBRs && cd ../..”

**Comment by Yushu-Li** [comment]
Thank you for reaching out and for your interest in our work. I apologize for the inconvenience caused by the broken link. I've updated the link to the pre-trained ResNet50 model for both CIFAR10 and CIFAR100, and you should be able to access it now via:

"mkdir -p results/cifar10_joint_resnet50 && cd results/cifar10_joint_resnet50
gdown https://drive.google.com/uc?id=1QWyI8UrXJ6_H9lBbrq52qXWpjdpq4PUn && cd ../..
mkdir -p results/cifar100_joint_resnet50 && cd results/cifar100_joint_resnet50
gdown https://drive.google.com/uc?id=1cau93HVjl4aWuZlrl7cJIMEKBxXXunR9 && cd ../.."

**Comment by ynanwu** [comment]
Thank you for your prompt response and for providing the updated links. I
appreciate your effort in resolving the issue.

Best Regards
Yanan

Yushu Li ***@***.***> 于2024年12月25日周三 12:20写道：
